### ISSUE TITLE
Stale EVM version causes traces to be incorrect

### ISSUE THREAD

**Issue by bout3fiddy** [vyperlang/titanoboa#105]
Issue:

![telegram-cloud-photo-size-4-5958519369850010945-y](https://github.com/vyperlang/titanoboa/assets/11488427/9651f4f7-22fb-4e13-af1b-f858e56de005)

The compiler says there is a `compiler: user assert`, which would look something like:

```vyper
assert 0 > 1, "Zero is not greater than 1"
```

The issue here is that the contract is compiled using `# pragma evm-version paris`, but for whatever reason, boa thinks it is `# pragma evm-version shanghai`.

The Offending commit is : https://github.com/vyperlang/titanoboa/commit/7171aee25c4d25fc1626a361a8c972e9316fd383

And before this commit, this error is correctly traced, and since this commit it is not.

Tips on how to resolve: 

(From Charles) In boa: protect the codegen with correct evm version, but protect source map generation in the same way.

**Comment by charles-cooper** [comment]
i believe this was fixed in e927974d70ae1d89f36a2a2170e89fc34b726dd6. please reopen if it's still an issue!
