### ISSUE TITLE
boa.test address strategy is not aligned with boa.env.generate_address()

### ISSUE THREAD

**Issue by bout3fiddy** [vyperlang/titanoboa#112]
how boa.test generates addresses: https://github.com/vyperlang/titanoboa/blob/f879b3d35c1fb980aa61d18256a8638eb5b952c9/boa/test/strategies.py#L101

how boa.env generates addresses:
https://github.com/vyperlang/titanoboa/blob/f879b3d35c1fb980aa61d18256a8638eb5b952c9/boa/environment.py#L579

unify these.

**Comment by MukulKolpe** [comment]
Hey @bout3fiddy, can I work on this issue?

**Comment by charles-cooper** [comment]
> Hey @bout3fiddy, can I work on this issue?

go for it

**Comment by charles-cooper** [comment]
what's the issue here? `boa.env.generate_address()` is kind of deterministic

**Comment by DanielSchiavini** [comment]
if this is by design, can we close the issue?

**Comment by charles-cooper** [comment]
fixed, as of b6eacad8 the address strategy returns `Address` type
