### ISSUE TITLE
Implement RPC via browser wallet

### ISSUE THREAD

**Issue by charles-cooper** [vyperlang/titanoboa#119]
it would be cool to get the RPC url from the browser signer (h/t @bout3fiddy for the idea), but out of scope here. will open a new issue for it

_Originally posted by @charles-cooper in https://github.com/vyperlang/titanoboa/issues/109#issuecomment-1893965908_

**Comment by DanielSchiavini** [comment]
We could not figure out a way to get the RPC URL from the frontend, it might be hidden for security purposes (it often contains API keys).
An alternative would be to introduce a separate `BrowserEnv` that implements `NetworkEnv` via the browser
