### ISSUE TITLE
Set chain_id via BrowserRPC

### ISSUE THREAD

**Issue by bout3fiddy** [vyperlang/titanoboa#125]
allow notebook author to set chainID on browsersigner:

currently we do:

```
import boa
from boa.integrations.jupyter import BrowserEnv
boa.set_env(BrowserEnv())

```

what i propose:

```
import boa
from boa.integrations.jupyter import BrowserEnv

browser_env_ethereum = BrowserEnv(chain_id=1)

boa.set_env(browser_env_ethereum)

```

**Comment by DanielSchiavini** [comment]
This doesn't seem to be part of the standard but it does seem to work for metamask: https://eips.ethereum.org/EIPS/eip-3326

@bout3fiddy `chain_id` instead of `chainId` pls
