### ISSUE TITLE
Notify user of tx fail in boa call output

### ISSUE THREAD

**Issue by bout3fiddy** [vyperlang/titanoboa#138]
Not sure how to do this but this tx to create a contract failed: https://bscscan.com/tx/0x77967045c0b62986ad3cf8933c746dff0b448dbffb2e71b89869e64ff54d1012

but boa returned an address (when nothing was deployed).

so there needs to be some sort of a check to tell the user that the tx failed

**Comment by DanielSchiavini** [comment]
[eth_getTransactionReceipt](https://www.quicknode.com/docs/ethereum/eth_getTransactionReceipt) returns a status (`0`/`1`) that we are not currently checking.

It's still weird that in your case the `eth_estimateGas` returned the wrong amount.
