### ISSUE TITLE
Jupyter plugin uses too much space

### ISSUE THREAD

**Issue by DanielSchiavini** [vyperlang/titanoboa#157]
The files generated when using our jupyter plugin are too large. Jupyterlab saves every JS that has ever ran in the notebook file.
That includes many copies of EthersJS - so the file gets multiple MBs of unnecessary JS.

**Comment by bout3fiddy** [comment]
Does this translate to call execution speed? I noticed it being slow.

**Comment by DanielSchiavini** [comment]
Fixed in https://github.com/vyperlang/titanoboa/pull/163
