### ISSUE TITLE
Error when running boa in vyper project folder

### ISSUE THREAD

**Issue by imachonky** [vyperlang/titanoboa#16]
Generally when running some boa commands that imports `vyper.version` like `boa.env` throws an error `ModuleNotFoundError: No module named 'vyper.version'` when running from locally cloned vyper project folder.

This is due to `sys.path` searching for vyper locally before installed packages.

Thinking to add a line on README.md reflecting this and how to fix.

**Comment by charles-cooper** [comment]
marking closed as of #17

**Comment by charles-cooper** [comment]
note: you can also run `pip install <path to local vyper install>` to install vyper in your local path
