### ISSUE TITLE
code coverage crashses with segfault

### ISSUE THREAD

**Issue by AlbertoCentonze** [vyperlang/titanoboa#175]
# version/specs
Architecture: Apple Silicon (M2 Pro)
Python version: `3.10.13`

# how to reproduce
1. Clone the [following repository](https://github.com/AlbertoCentonze/snake-silo/tree/890710c9b501f686294e35ca2ae63a66ecfda344)  at the specified commit.
2. Install dependencies and the correct python version using `poetry install`
3. Run the tests with `poetry run coverage run -m pytest`

**Comment by charles-cooper** [comment]
what version of python / OS are you using?

**Comment by AlbertoCentonze** [comment]
Just updated the issue, sorry for forgetting about that.

Probably worth mentioning that I tried out again with a more recent version of boa and the error is different (not segfaulting anymore). To reproduce the new error it suffices to clone the repo from this [more recent commit](https://github.com/AlbertoCentonze/snake-silo/tree/c8978b20688db46193ffb426a56e86c809f41947) and then the steps for reproduction are the same.

Here's the new [error](https://github.com/vyperlang/titanoboa/files/14464051/error.txt)

**Comment by charles-cooper** [comment]
oof -- we might not even be getting to the segfault anymore.

**Comment by charles-cooper** [comment]
resolved -- do not use coverage with `boa.env.enable_fast_mode()`! (it may work in the future, but does not at this time)
