### ISSUE TITLE
titanoboa-0.1.9 incompatible with py-evm>=0.10.0

### ISSUE THREAD

**Issue by ritzdorf** [vyperlang/titanoboa#193]
I did
```
pip install titanoboa
```
which installs `titanoboa-0.1.9` and
```
import boa
boa.eval("empty(uint256)")
```

I get
```
TypeError: titanoboa_computation.apply_computation() got an unexpected keyword argument 'parent_computation'
```

I get this for different python versions (3.10 and 3.11) and different types of code. It seems that the installation is broken. It works for `0.1.8`.

**Comment by charles-cooper** [comment]
titanoboaboa 0.1.9 is not compatible with latest py-evm, you should install from master or downgrade to py-evm<0.10.0

**Comment by DanielSchiavini** [comment]
I think we can close this with the release https://github.com/vyperlang/titanoboa/releases/tag/v0.1.10b1?
