### ISSUE TITLE
feat: expose private constants

### ISSUE THREAD

**Issue by AlbertoCentonze** [vyperlang/titanoboa#196]
As per title, would be nice to access private constant variables with `_constant` in the same way it is already possible for `_immutable` and `_storage` private variables.

BONUS: would be great if we could also access them from `VyperDeployer` since they are available before deployment.

**Comment by DanielSchiavini** [comment]
Just to clarify: We are exposing the private constants in the deployer level as they can be used directly at compile time for inspection, testing, etc

**Comment by charles-cooper** [comment]
done in #215
