### ISSUE TITLE
Forked caching does not work

### ISSUE THREAD

**Issue by sajal** [vyperlang/titanoboa#205]
It seems caching is not working as it should. 

I installed `plyvel` manually , and with liberal use of print statements in [boa/vm/fork.py](https://github.com/vyperlang/titanoboa/blob/ed545f27bc9cea5d4239e84aa3afe6677aba9ccd/boa/vm/fork.py). I observe `self._db` is the leveldb backed database at the end of `__init__` , however during all fetch_multi calls, its value is MemoryDB({}) 

It appears that something is calling `_init_mem_db` and `__init__` multiple times and between each usage of the cache, this in-effect disables both memory and disk cache.

**Comment by charles-cooper** [comment]
should be fixed in f84bad9cd437132dec9a1f2c3dc7f007bfb5fb43. thanks for the report!
