### ISSUE TITLE
Enable coverage support for vyper 0.4

### ISSUE THREAD

**Issue by AlbertoCentonze** [vyperlang/titanoboa#251]
Currently, it is not possible to obtain the coverage of a vyper module.

**Comment by DanielSchiavini** [comment]
@AlbertoCentonze @charles-cooper is this still an issue? A few PRs were merged regarding coverage:
![Image](https://github.com/user-attachments/assets/da5ac226-284b-4169-8d79-115da54259c6)

**Comment by charles-cooper** [comment]
yea, there's some small issues here and there but we can close this
