### ISSUE TITLE
parse_to_ast missing? 

### ISSUE THREAD

**Issue by PatrickAlphaC** [vyperlang/titanoboa#254]
titanoboa==0.1.9

I have the following line:

```python
from boa import VyperDeployer, load_partial

load_partial(contract_path, "titanoboa", "boa", 18, 1)
```

```
 File "/Users/patrick/code/gaboon/.venv/lib/python3.12/site-packages/boa/__init__.py", line 5, in <module>
    from boa.contracts.vyper.vyper_contract import check_boa_error_matches
  File "/Users/patrick/code/gaboon/.venv/lib/python3.12/site-packages/_pytest/assertion/rewrite.py", line 178, in exec_module
    exec(co, module.__dict__)
  File "/Users/patrick/code/gaboon/.venv/lib/python3.12/site-packages/boa/contracts/vyper/vyper_contract.py", line 18, in <module>
    from vyper.ast.utils import parse_to_ast
ImportError: cannot import name 'parse_to_ast' from 'vyper.ast.utils' (/Users/patrick/code/gaboon/.venv/lib/python3.12/site-packages/vyper/ast/utils.py)
```

Am I doing something wrong?

**Comment by charles-cooper** [comment]
Seems like an installation issue. Do you have vyper 0.4.0 installed?

**Comment by PatrickAlphaC** [comment]
Yes. It looks like `0.1.19` is the latest version, but it should be `0.1.18`.

https://pypi.org/project/titanoboa/0.1.9/

Maybe it make sense to add to github actions an auto release so that the versions always match ?

**Comment by charles-cooper** [comment]
> Maybe it make sense to add to github actions an auto release so that the versions always match ?

yea we should do that, just not really a priority

> Yes. It looks like 0.1.9 is the latest version, but it should be 0.1.8.

no, 0.1.9 latest is correct. i think the issue you are running into is 0.1.9 needs vyper 0.3.10 but you have 0.4.0 installed

**Comment by charles-cooper** [comment]
closing as wontfix, this is a dependency resolution issue in the user project
