### ISSUE TITLE
log events without eval

### ISSUE THREAD

**Issue by bout3fiddy** [vyperlang/titanoboa#26]
Currently one needs to do:

```
token_contract.eval(f"log Transfer(empty(address), {addr}, {amount})")
```

make it so that:

```
token_contract.log.Transfer(0x0, addr, amount)
```

**Comment by charles-cooper** [comment]
what's the use case for this?

**Comment by bout3fiddy** [comment]
testing.

**Comment by bout3fiddy** [comment]
For me, this comes from the code I use to mint coins. Currently:

```
import boa
from eth_utils import to_checksum_address


def mint_for_testing(token_contract, addr, amount):

    addr = to_checksum_address(addr)

    if token_contract.symbol() == "WETH":
        boa.env.set_balance(addr, boa.env.get_balance(addr) + amount)
        with boa.env.prank(addr):
            token_contract.deposit(value=amount)
    else:
        token_contract.eval(f"self.total_supply += {amount}")
        token_contract.eval(f"self.balanceOf[{addr}] += {amount}")
        token_contract.eval(f"log Transfer(empty(address), {addr}, {amount})")
```

My logic was perhaps (instead of `eval`) we could do something that is a bit more cached so that tests ran faster. Or perhaps we should have built-in features for minting test tokens? I would love to hear your thoughts on this.

**Comment by charles-cooper** [comment]
I mean, for this use case -- you can just use a private function which isn't used in the contract itself. This would be stripped from the bytecode of a production build, but it would be available from the `contract.internal` namespace.

```vyper
@internal
def test_mint(addr: address, amt: uint256):
    self.total_supply += amt
    self.balanceOf[addr] += amt
    log Transfer(empty(address), addr, amt)
```

and then call `my_contract.internal.test_mint(addr, amount)`.

**Comment by charles-cooper** [comment]
to make this more convenient so that you don't need to add dead code to your contract - i added a dynamic function injecter in https://github.com/vyperlang/titanoboa/commit/88b9c7cfe7cc3c2f0c68427d45945b3a24f9e21c
