### ISSUE TITLE
make timetravel api cleaner

### ISSUE THREAD

**Issue by bout3fiddy** [vyperlang/titanoboa#28]
right now, if one wants to time travel:

```
import boa

def boa_sleep(sleep_time):
    boa.env.vm.patch.timestamp += sleep_time
    boa.env.vm.patch.block_number += sleep_time // 12
```

this can be under the boa.env umbrella instead, such that:

```
boa.env.time_travel(sleep_time)
```

adding this feature to `boa > environements.py > Env` closes this issue

**Comment by charles-cooper** [comment]
we can roll the two lines into one function, but i think it should stay under the vm patcher for now.

fwiw dapptools / foundry uses `roll()` as the terminology for this.

**Comment by charles-cooper** [comment]
nvm, just double checked and `roll()` modifies block.number, `warp()` modifies block.timestamp
