### ISSUE TITLE
`get_gas_used` returns too high numbers with multiple functions in the same contract

### ISSUE THREAD

**Issue by pcaversaccio** [vyperlang/titanoboa#62]
In order to reproduce this bug you can use my [`Math.vy`](https://github.com/pcaversaccio/snekmate/blob/main/src/utils/Math.vy) here.

If you do the following (calling the function `is_negative`) you will get `338` gas usage.

```
>> import boa
>> c = boa.load("src/utils/Math.vy")
>> c.is_negative(-13)
True
>> c._computation.get_gas_used()
338
```

However that's actually the wrong figure since if you put only the function into an empty contract `Math2.vy`, you will get the correct figure of `131`. And this around `+200` gas usage is consistent across other functions. So the contract size somehow messes with the gas computation which should not be the case.

![image](https://user-images.githubusercontent.com/25297591/222757458-65076eb7-df5f-4dec-ba0c-64b1747c494d.png)

**Comment by charles-cooper** [comment]
this is not a bug, because boa reproduces the runtime behavior correctly, which is that for external functions, you need to traverse the method dispatch table in order to call an external function.
