### ISSUE TITLE
bug: latest docs not showing

### ISSUE THREAD

**Issue by tserg** [vyperlang/titanoboa#71]
The [documentation](https://titanoboa.readthedocs.io/en/latest/index.html) does not reflect the `latest` version. I am not sure how this can be fixed.

**Comment by charles-cooper** [comment]
there seems to be some issue with builds lately, ex. https://readthedocs.org/projects/titanoboa/builds/20188750/. I can't reproduce on a PR, for instance https://github.com/vyperlang/titanoboa/pull/74 looks like a good build

**Comment by tserg** [comment]
Same, I cannot reproduce the error too - looks like it is only failing on `latest`. Based on the docs, [switching](https://docs.readthedocs.io/en/stable/guides/pdf-non-ascii-languages.html) the LaTeX engine should fix the unicode error, but it is at best a guess.

**Comment by charles-cooper** [comment]
i added a `.readthedocs.yaml` config in #76, which seems to have fixed the issue
