### ISSUE TITLE
feature: jupyterlab extension

### ISSUE THREAD

**Issue by charles-cooper** [vyperlang/titanoboa#83]
it would be cool to have https://github.com/vyperlang/titanoboa/blob/2c2a2664ad3fa566ddda8a43851cd6f14ab9276a/boa/integrations/jupyter.py work with jupyterlab (on account of jupyterlab being the new thing, it has an IDE and workspace etc). the current method for loading `ethers` does not seem to work though, it fails with `require not defined`, seems to be related to https://github.com/Calysto/calysto_processing/issues/11#issuecomment-432943286. it looks like the thing to do is write a proper jupyterlab extension, which would be cool too since we could support vyper files natively.

**Comment by charles-cooper** [comment]
also debugger (cf. https://jupyterlab.readthedocs.io/en/stable/user/debugger.html) and kernel for vyper could be done

**Comment by DanielSchiavini** [comment]
Is the idea here to simply port the existing code into a proper plugin, or do we want to add/change the functionality as well?
If so it would be great to know what the new functions we want implement are (maybe in separate issues?)

**Comment by DanielSchiavini** [comment]
I created a plugin template in https://github.com/DanielSchiavini/titanoboa-jupyterlab

**Comment by charles-cooper** [comment]
btw, does this technique work with google colab somehow?

**Comment by DanielSchiavini** [comment]
We definitely don't need any extra dependencies, this was an easy way to proof the concept.
About Collab, I have no idea, and I wasn't able to find the restrictions quickly today. I can investigate more.

**Comment by DanielSchiavini** [comment]
The integration tests are failing in Github for some stupid reason (they pass locally).
I've managed to reproduce the issue locally, and track down an exception thru [act](https://github.com/nektos/act), docker and jupyterlab to [this line](https://github.com/jupyterlab/jupyterlab/blob/c26a0e7cced6eea64a7f0908a7cded8e4c8874fb/jupyterlab/staging/index.js#L49-L52). It produces `["TypeError: Cannot read properties of undefined (reading 'get')","TypeError: Cannot read properties of undefined (reading 'get')"]` which is about the most generic error in the planet and it can come from literally anywhere. And the error details are right there being ignored in the line. :angry: 
I'm trying to intercept the call somehow but it's not easy inside Github actions :disappointed:

**Comment by DanielSchiavini** [comment]
I have 3 PRs with the implementation ready for review:
- https://github.com/vyperlang/titanoboa/pull/109
- https://github.com/vyperlang/try.vyperlang.org/pull/1
- https://github.com/DanielSchiavini/titanoboa/pull/1
